### ISSUE TITLE
React-native-video

### ISSUE THREAD

**Issue by waheed25** [Microsoft/reactxp#223]
i am trying to run hello world-js example but when i run npm start command in terminal or when i am trying to build in android studio it shows me error of react-native-video and react-native-svg

**Comment by dryganets** [comment]
@waheed25, thank you for the report.
This issue fixed in the master.
Run npm install in the sample directory and try it out with new dependencies.

**Comment by waheed25** [comment]
Thanks but After Ur referenced solution i am getting error of react-native-svg i install it through npm but error is changed while building this project in android studio but not solved

**Comment by waheed25** [comment]
problem solved with importing package import com.horcrux.svg.RNSvgPackage; 
instead of
import com.horcrux.svg.SvgPackage;
