### ISSUE TITLE
(How to) Disable GestureView in underlying layers?

### ISSUE THREAD

**Issue by shameister** [Microsoft/reactxp#835]
Hello,

we use a `RX.GestureView` inside a `RX.ScrollView` to recognize pan gestures. In case something is rendered above our view (wich can happen without our view knowing), we would like to disable the feature, that the GestureView receives the gestures.

I expected, there might be a way *like* `state.stopPropagation()`, so I could implement an own RX.GestureView in my blurred alpha background view, which absorbs all events.

![bildschirmfoto 2018-10-02 um 18 08 08](https://user-images.githubusercontent.com/98413/46361735-a9aa1b80-c66e-11e8-9e6e-2b0601e6414a.png)

In my case, you are able to move/resize the overlayed views, which is really not desired.

Looking forward for a suggestion to solve this. Am I missing something?

Regards,
Sascha

**Comment by erictraut** [comment]
It sounds like you want the dialog box to act modally. Do you use an RX.Modal for rendering the dialog box? That should prevent interaction with anything behind it.

**Comment by shameister** [comment]
Our `BlurredBackground` is a plain `RX.View` with just a style tweak to blur on web:

```
import RX = require('reactxp');

interface BlurredBackgroundProps {
  onPress?:(event:RX.Types.MouseEvent) => void
}

const styles = {
  modalDialog: RX.Styles.createViewStyle({
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    alignSelf: 'center',
    alignContent: 'center',
    alignItems: 'stretch',
    justifyContent: 'center',
    ['backdropFilter' as string]: 'blur(2px)'
  }),
}

class BlurredBackground extends RX.Component<BlurredBackgroundProps, RX.Stateless> {

  render()
  {
    return (
      <RX.View style={ styles.modalDialog } onPress={ this.props.onPress } >
        { this.props.children }
      </RX.View>
    )
  }
}

export = BlurredBackground
```

**Comment by erictraut** [comment]
Are you seeing this problem on iOS (native) or on the web? Since you're talking about pan gestures, I'm guessing it's on iOS, but your screen shot above appears to be from the web version. In either case, I would expect that the touch gesture would be blocked by your modal background, which is in a completely different view sub-hierarchy than the views it is overlaying.

**Comment by shameister** [comment]
Currently we are targeting just the web platform (Electron). Just talking about pan gestures, as I use `RX.GestureView`s `onPanVertical`.

**Comment by erictraut** [comment]
Ah, so these are mouse-based gestures. I see that you have an onPress handler installed on the background view. Does that get called? I'm still unsure how the mouse events are getting through to the underlying view. Even if you don't call stopPropagation in your onPress handler, they should still have no way to bubble to the underlying views. The modal background view should be capturing all mouse events unless you explicitly set the ignorePointerEvents to true, which you're clearly not doing.

**Comment by shameister** [comment]
Yes, my `onPress`-handler also gets called. If you like, I can give you a demo via skype.

**Comment by shameister** [comment]
Yes, my `onPress`-handler also gets called. If you like, I can give you a demo via skype.

![demo video](https://user-images.githubusercontent.com/98413/46584598-911e7480-ca65-11e8-9b62-7ce3d96906aa.gif)

**Comment by erictraut** [comment]
I've coded up a fix for the problem. Please try it and tell me if it addresses your problem.
https://github.com/Microsoft/reactxp/pull/846

**Comment by shameister** [comment]
I tried to replace your files in my `node_modules/reactxp/src/web`, but did not know, how to get your source distributed, to get it running. Is there a way to set your patch as reactxp-version in my package.json, to test it?

**Comment by erictraut** [comment]
You should be able to check out my branch, build it (```npm run build```), and copy the resulting dist/* directory over the top of the node_modules/reactxp/dist/* in your app's sources.

**Comment by shameister** [comment]
I can't see your branch anywhere. I loaded your changed files manually into my RXP src folder, but was not able to rebuild it via `npm run build`, `npm run rebuild` and `npm install --build-from-source`. Could you provide the 5 distributed js files anywhere as a drop-in replacement?

**Comment by erictraut** [comment]
I've merged the change into master. You should be able to build it from there (```nom i``` and ```nom run build```).

**Comment by shameister** [comment]
I did not get it running so far, but I found out, that this issue also appears, if pushing another view inside a `Navigator`. The gesture is nontheless recognized. :-/

**Comment by yohan-pg** [comment]
I'm still having this problem with a non-modal view. Is the intended behavior for gestures to pass through views on desktop unless the view is a modal?

**Comment by erictraut** [comment]
@yohan-pg, can you explain your situation in more detail? What platform? What is your view hierarchy?

**Comment by yohan-pg** [comment]
@eictraut is there a better solution than adding other gesture views on top of the first to capture the events? Responder events don't seem to get called on RX.View on web and I haven't found any another way of capturing events. I'm not used to native event handling so maybe I'm missing something.

**Comment by erictraut** [comment]
I can't think of a better solution at this time, short of completely rethinking how RX.GestureView is implemented on the web.

**Comment by yohan-pg** [comment]
I'm not super familiar with how GestureView is implemented; what problem is assigning the listener to the window instead of the view trying to solve? Could it be possible to at least opt-in to having it assigned to the div (on web)?

**Comment by erictraut** [comment]
I'm not sure what problem it was trying to solve. It needs to support panning operations where the gesture view itself is moving in response to the pan gesture, but that could be accomplished by capturing the mouse upon mouse down. 

I think it's worth trying to address this, but I don't have time to do it now. You're welcome to do it and submit a PR if you're successful. I just added a CONTRIBUTIONS.md file that explains the process.

**Comment by shameister** [comment]
I just installed 1.5.0-rc.4 and experienced no change. The bug still remains.

**Comment by erictraut** [comment]
That's expected. No one has submitted a rewrite of the web implementation of GestureView.

**Comment by yohan-pg** [comment]
I'll look into this as soon as I have time
